config/routes.rb
FlatBlog2::Application.routes.draw do

  devise_for :users

  root :to => 'articles#index'

  resources :articles do
    resources :comments
    resources :votes
  end

  match 'articles/:id/update_rating' => 'articles#update_rating', :as => :update_rating, :via => 'get'
  match ':controller(/:action(/:id(.:format)))'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :body, :presence => true

  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy

  scope :above_a_certain_rating, lambda{|minimum_rating| where('rating > ?',minimum_rating).order('DATE(created_at) DESC, rating DESC').includes(:comments)}
  scope :below_a_certain_rating, lambda{|minimum_rating| where('rating <= ?',minimum_rating).order('DATE(created_at) DESC, rating DESC').includes(:comments)}

  CATEGORY = ['News', 'Sport', 'Humor', 'World']
  
  def vote!(user_ip)
    self.votes.create!(:user_ip => user_ip, :user_identity => (self.id.to_s + '#' + user_ip.to_s))
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, :body, :presence => true

  belongs_to :article, :counter_cache => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :recoverable,:timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :user_identity, :uniqueness => true
  
  belongs_to :article
  
protected
  def self.user_vote(user_ip)
    self.where("user_ip = ?", user_ip).map{|el| el.article_id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :article, :only => [:show, :edit, :update, :destroy, :update_rating]
  before_filter :user_vote, :only => [:index, :update_rating]
  before_filter :set_rating, :only => [:index]

  def index
    if params[:order]
      @articles = Article.below_a_certain_rating(@rating)
      @sort_text = "sort by date, rating more than " + @rating.to_s
    else
      @articles = Article.above_a_certain_rating(@rating)
      @sort_text = "sort by date, rating less than " + @rating.to_s

    end
    respond_to do |format|
      format.html
      format.xml  { render :xml => @articles }
    end
  end

  def show
    @comments = @article.comments
    respond_to do |format|
      format.html
      format.xml  { render :xml => @article }
    end
  end

  def new
    @article = Article.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @article }
    end
  end


  def edit
  end

  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end



  def update_rating
    @remote_ip = request.remote_ip
    if @user_vote.grep(@article.id).count.zero?
      @article.vote!(@remote_ip)
      @article.rating += params[:value].to_i
      if @article.save
        respond_to do |format|
          format.html {redirect_to(articles_path, :notive => "Your vote accepted!")}
          format.js {}
        end
      end
    end
  end


  def user_vote
    @user_vote = Vote.user_vote(request.remote_ip())
  end

  def article
    @article = Article.find(params[:id])
  end

  def set_rating
    @rating = 3
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html {redirect_to(@article, :notice => 'Add comment')}
        format.xml {render :xml => @article, :status => :created, :location => @article}
      else
        format.html {redirect_to(@article, :notice => 'Comment was not saved, fill in all fields!')}
        format.xml {render :xml => @comment.errors, :status => :unprocessable_entity}
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def check_user_voted(article_id)
    @user_vote.grep(article_id).count.zero?
  end

  def sort_list
    if params[:order]
      articles_path
    else
      articles_path(:order => true)
    end
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_article.html.erb
  <li id='<%= dom_id(article) %>'>
    <h3><%= link_to article.title, article %></h3>
    <p>Category <%= article.category %>. Posted <%= article.created_at %></p>
    <p><%= article.body %></p>
    <div>
      <% if(user_signed_in?) %>
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
      <% end %>
    </div>
    <ul>

      <li><%= link_to(pluralize(article.comments.size,'comment'), article) %></li>
      <li>url: <%= article.url %></li>
      <li>tags: <%= article.tags %></li>
      <li>rating:
        <% if check_user_voted(article.id) %>
          <%= link_to '[+]', update_rating_path(article, :value => 1), :remote => true %>
          <span class="rating"><%= article.rating %></span>
          <%= link_to '[-]', update_rating_path(article, :value => -1), :remote => true %>
        <% else %>
          <span class="rating"><%= article.rating %></span>
        <% end %>
      </li>
    </ul>
  </li>


app/views/articles/_comment_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_field :name %>
    <%= f.label :name %>
  </p>
  <p>
    <%= f.text_area :body, :rows=>10, :cols=>"100%" %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>


app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :url %>
    <%= f.label :url %><br />
  </div>
  <div class="field">
    <%= f.text_field :tags %>
    <%= f.label :tags %><br />
  </div>
  <div class="field">
    <%= f.select :category, Article::CATEGORY %>
    <%= f.label :category %><br />
  </div>
  <div class="field">
    <%= f.text_field :title %>
    <%= f.label :title %><br />
  </div>

  <div class="field">
    <%= f.text_area :body %>
  </div>

  <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3>Editing article</h3>
<br />
<ul id='article_panel'>
  <li><%= link_to 'Show', @article %></li>
  <li><%= link_to 'Back to articles', articles_path %></li>
</ul>
<br />
<%= render 'form' %>

app/views/articles/index.html.erb
<div id='keys'>
  <p><%= link_to 'New Article', new_article_path %></p>

  <p><%= link_to @sort_text, sort_list %></p>
</div>
<ul>
  <%= render @articles %>
</ul>

app/views/articles/new.html.erb
<h3>New article</h3>
<br />
<ul id='article_panel'>
  <li><%= link_to 'Back', articles_path %></li>
</ul>

<br />
<%= render 'form' %>

app/views/articles/show.html.erb
<ul id='function_panel'>
  <li><%= link_to 'Back to articles', articles_path %></li>
</ul>
<h3><%= @article.title %></h3>
<p>Category <%= @article.category %>. Posted <%= @article.created_at %></p>
<p><%= @article.body %></p>

<ul id="article_panel">
  <li><%= link_to 'Edit', edit_article_path(@article) %></li>
  <li>url: <%= @article.url %></li>
  <li>tags: <%= @article.tags %></li>
</ul>

<h4><%= pluralize(@comments.size, "comment") %> on <%= @article.title %></h4>
<ul id="comment_list"><%=render @comments %></ul>
<div id="writecomment">
  <%= render 'comment_form' %>
</div>

app/views/articles/update_rating.js.erb
$(function(){
  $("li#article_<%= @article.id %> ul li:last-child").html('rating: <span class="rating"><%= @article.rating %></span>');
})

app/views/comments/_comment.html.erb
  <li>
    <span><%= comment.name %></span>
    said <%= comment.created_at.to_date %>
    <p><%= comment.body %></p>
  </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatBlog2</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag 'jquery.min', 'rails', 'application' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="title">
      <div>
        <h1>FlatBlog&sup2;</h1>
        <p>Test job at the rate of training of Ruby on Rails programmers from FlatSoft company</p>
      </div>
      <div>
        <%if user_signed_in? %>
          <!-- for signed user -->
          Hi, <%= current_user.name %> (<%= current_user.email %>) &nbsp;|
          <%= link_to 'New Article', new_article_path %>&nbsp;|
          <%= link_to 'Edit profile', edit_user_registration_path %>&nbsp;|
          <%= link_to 'Sign out', destroy_user_session_path %>&nbsp;

         <% else %>
          <!-- for unsigned user -->
          <%= link_to 'Login', new_user_session_path %>&nbsp;|
          <%= link_to 'Registration', new_user_registration_path %>&nbsp;
         <% end %>
       </div>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <div id="content">
      <%= yield %>
    </div>
    <div id="footer"></div>
  </body>
</html>